# Site settings
title: My blog
header-img: img/home-bg.png
email: matbalez@gmail.com
copyright_name: matbalez
description: > # this means to ignore newlines until "baseurl:"
  is great
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: matbalez
github_username:  matbalez
learn_profile: matbalez
email_username: matbalez@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
